### ISSUE TITLE
Test an adv_image 

### ISSUE THREAD

**Issue by zytxxn** [AlonZolfi/AdversarialMask#3]
Could you please tell me how to test whether an adv_image can be recognized as unknown? Thank you very much!

**Comment by AlonZolfi** [comment]
Being recognized as unknown means that the similarity between the ground truth embedding of the person and the embedding of an adv image is lower than a pre-defined threshold.
This threshold is system-dependant and should be chosen according to the system requirements.
The way we chose our threshold is listed in the paper under "physical attack setup" section.

**Comment by silvercherry** [comment]
> Could you please tell me how to test whether an adv_image can be recognized as unknown? Thank you very much!

Have you finished the training, the pure white of the mask I got after training
