### ISSUE TITLE
target attack

### ISSUE THREAD

**Issue by zytxxn** [AlonZolfi/AdversarialMask#4]
Hi! Is "train_multiple.py" able to achieve target attack?

**Comment by AlonZolfi** [comment]
the train_multiple.py script was used to create an adversarial mask that is tailor-made for each identity.
So, if by "targeted attack" you mean a mask that is optimized on one specific identity the answer is yes.
Otherwise, if meant that a mask will be optimized to impersonate a target identity, that would require some changes in the loss function.

**Comment by zytxxn** [comment]
Thank you for your  reply. I mean that a mask will be optimized to impersonate a target identity. How do I change  the loss function?

**Comment by AlonZolfi** [comment]
The loss function should include another term that maximizes the cosine similarity between the target identity embedding to the adversarial embedding.
So that would require a similar term as the $\ell_{sim}$ in the original paper, but with a preceding minus sign since we aim to increase this term.

**Comment by silvercherry** [comment]
> Hi! Is "train_multiple.py" able to achieve target attack?

Have you finished the training, the pure white of the mask I got after training

**Comment by zytxxn** [comment]
> 

Maybe you run "train_multiple.py"? I also got the white mask.

**Comment by silvercherry** [comment]
> > 
> 
> Maybe you run "train_multiple.py"? I also got the white mask.

I get white mask in both 'train.py' and 'train_multiple.py'... have you solve it?

**Comment by zytxxn** [comment]
> > > 
> > 
> > 
> > Maybe you run "train_multiple.py"? I also got the white mask.
> 
> I get white mask in both 'train.py' and 'train_multiple.py'... have you solve it?

I got the correct mask by 'train.py', I don't know why you were wrong. Maybe your train images are not enough or Less training?

**Comment by silvercherry** [comment]
> > > > 
> > > 
> > > 
> > > Maybe you run "train_multiple.py"? I also got the white mask.
> > 
> > 
> > I get white mask in both 'train.py' and 'train_multiple.py'... have you solve it?
> 
> I got the correct mask by 'train.py', I don't know why you were wrong. Maybe your train images are not enough or Less training?

Could you please email more details? my email is sunchunyu1211@163.com
