### ISSUE TITLE
Question about the digital pattern printed on paper

### ISSUE THREAD

**Issue by oaapao** [AlonZolfi/AdversarialMask#6]
Hi! Since the digital adversarial mask was trained on the ResNet100@ArcFace and was (3,60,112), the size of the digital pattern printed on paper which will be put on human face later will be much larger than (60,112), how do you upsample the adversarial mask?

**Comment by AlonZolfi** [comment]
To avoid large downsampling from a higher resolution, we preferred to use a small digital mask.
To print it in the real world, we manually resized it to the correct size.
